stages:
  - test
  - build

default:
  tags:
    - docker

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends make gcc gcc-avr avr-libc binutils-avr

unit_tests:
  stage: test
  image: debian:bookworm-slim
  script:
    - make test

build_firmware:
  stage: build
  image: debian:bookworm-slim
  script:
    - make avr
  artifacts:
    paths:
      - build/uart_keyboard.elf
      - build/uart_keyboard.hex
    expire_in: 1 week
